#!/bin/sh

PACKAGES_LIBS="libblkid1 libbz2-1.0 libc6 libc-bin libcrypt1 libeudev1 libkmod2 liblzma5 libmagic1 libmagic-mgc libncurses6 
libncursesw6 libpcre2-8-0 libselinux1 libsemanage1 libsemanage-common libsepol1 libslang2 libssl1.1 libtinfo6 lsb-base 
ncurses-base ncurses-bin zlib1g "

PACKAGES="bash eudev file "

rm packages/base/*.deb
cd packages/base

echo "[pkg-base] Downloading packages"
apt-get download $PACKAGES

echo "[pkg-base] Downloading package libs"
apt-get download $PACKAGES_LIBS
cd ../..

