#!/bin/sh

PACKAGES_LIBS="libaudit-common libbrotli1 libbsd0 libcap2 libdbus-1-3 libdrm2 libdrm-common libedit2 
libegl1 libelf1 libepoxy0 libevdev2 libexpat1 libfontconfig1 libfontenc1 libfreetype6 libgbm1 libgcc-s1 
libgl1 libglvnd0 libglx0 libice6 liblocale-gettext-perl liblz4-1 libmd0 libmtdev1 libpciaccess0 libpixman-1-0 
libpng16-16 libsensors5 libsensors-config libsm6 libstdc++6 libsystemd0 libunwind8 libutempter0 libvulkan1 
libwayland-client0 libwayland-server0 libx11-6 libx11-data libx11-xcb1 libxau6 libxaw7 libxcb1 libxcb-dri2-0 
libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-shm0 libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcursor1 
libxdamage1 libxdmcp6 libxext6 libxfixes3 libxfont2 libxft2 libxi6 libxinerama1 libxkbfile1 libxmu6 libxmuu1 
libxpm4 libxrandr2 libxrender1 libxshmfence1 libxss1 libxt6 libxtst6 libxvmc1 libxxf86vm1 libz3-4 libzstd1 "

PACKAGES="x11-common x11-xkb-utils xbitmaps xfonts-100dpi xfonts-75dpi xfonts-encodings xfonts-utils xinit 
xkb-data xserver-common xserver-xorg-core xserver-xorg-input-evdev xserver-xorg-video-vesa xserver-xorg-video-fbdev 
fontconfig fontconfig-config keyboard-configuration x11-xserver-utils "

rm packages/xorg/*.deb
cd packages/xorg

echo "[pkg-xorg] Downloading packages"
apt-get download $PACKAGES

echo "[pkg-xorg] Downloading package libs"
apt-get download $PACKAGES_LIBS
cd ../..

