#!/bin/busybox ash
#	rcS script for Anmincat Linux
#	Modified by Supphakit Duanghoy (c) 2022
#	Original from https://github.com/cross-lfs/bootscripts-embedded/blob/master/clfs/rc.d/startup

. /etc/init.d/services/functions
. /etc/os-release

dmesg -n 1
clear
echo -e '\e[1;37m/\_/\'
echo '( o.o )'
echo -e ' > ^ <\e[0m'
echo -e "Anmincat Linux \e[1;35m${VERSION}\e[0m Running Linux Kernel \e[1;35m$(uname -r)\e[0m"
echo -e "Anmincat is free \e[1;33m(GPLv2)\e[0m live mini rescue system."
echo -e "\e[1;31mRemember! Anmincat comes with ABSOLUTELY NO WARRANTY! \e[0m"
echo
sleep 2

mount -t devtmpfs none /dev
mount -t proc none /proc
mkdir -p /dev/pts
mkdir -p /dev/shm

echo -n "Mounting fstab..."
mount -a
check_status

echo -n "Remounting root rw..."
mount -o remount,rw /
check_status

echo -n "Setting language to C..."
LANG=C
export LANG LC_ALL
check_status

echo -n "Setting hostname to $(cat /etc/hostname)..."
hostname $(cat /etc/hostname)
check_status

echo -n "Setting up interface lo..."
ifconfig lo up 127.0.0.1
check_status

echo "Starting services..."

for i in /etc/init.d/start/*
do
	if [ -x $i ]; then
		$i start
	fi
done

echo
echo "Welcome to Anmincat $VERSION!"
echo
exit 0
