#!/bin/sh
#	ethernet-setup-dhcp is a shell script, DHCP automatic ethernet setup.
#	Made by Supphakit Duanghoy (c) 2022

echo "Checking eth0..."
if [ "$(ip addr | grep eth0)" = ""  ]; then
	echo "eth0 not found."
	echo "Maybe your network driver/controller not included or unloaded?"
	echo "Press any keys to quit..."
	read
	exit 1
else
	echo "Found."
fi

echo "Creating network.conf..."
printf "NETWORKING=yes\nINTERFACE=eth0\nDHCP=yes" > /etc/network.conf

echo "Creating /etc/network.d/interface.eth0..."
touch /etc/network.d/interface.eth0

echo "Creating /etc/network/interfaces..."
printf "auto lo\niface lo inet loopback\n\nauto eth0\niface eth0 inet dhcp\nudhcpc_opts -b" > /etc/network/interfaces

echo "Running network service..."
/etc/init.d/services/network start

echo "Finished!"
echo "Press enter to close..."
read
