#!/bin/sh
printf "[filesystem] Checking if old system directory is available..."
if [ -d ${PWD}/system ]; then
	printf "yes, deleting...\n"
	rm -rf system
else
	printf "no\n"
fi

echo "[filesystem] Creating filesystem structure for system/ ..."
mkdir -pv system/etc
mkdir -v system/bin
mkdir -v system/sbin
mkdir -v system/lib
mkdir -v system/dev
mkdir -v system/tmp
mkdir -v system/sys
mkdir -v system/proc
mkdir -v system/home
mkdir -v system/mnt
mkdir -v system/opt
mkdir -v system/run
mkdir -pv system/var/log
mkdir -v system/var/run
mkdir -pv system/usr/local
mkdir -v system/usr/local/bin
mkdir -v system/usr/local/sbin
mkdir -v system/usr/local/lib
mkdir -v system/usr/local/share
mkdir -v system/usr/local/etc
mkdir -v system/usr/share
mkdir -v system/usr/lib
mkdir -v system/usr/bin
mkdir -v system/usr/sbin

echo "[filesystem] Creating /etc/network.d..."
mkdir system/etc/network.d

echo "[filesystem] Creating /etc/network/if-*.d folders..."
mkdir -p system/etc/network/if-post-up.d
mkdir system/etc/network/if-post-down.d
mkdir system/etc/network/if-up.d
mkdir system/etc/network/if-down.d
mkdir system/etc/network/if-pre-up.d
mkdir system/etc/network/if-pre-down.d

case $(uname -m) in
	x86_64) mkdir -v system/lib64 ;;
esac

install -dv -m 0750 system/root
mkdir -pv system/root/.local/share

echo "[filesystem] Creating device nodes..."	
mknod -m 600 system/dev/console c 5 1
mknod -m 666 system/dev/null c 1 3

echo "[filesystem] Finished!"
