#!/bin/sh

echo
echo "Now installing tools packages..."
echo

for packages in packages/tools/*.deb; do
	echo "[tools] Installing $packages"
	dpkg -x $packages system/
done

echo "[tools] Installing grub4dos"
mkdir -v system/usr/lib/grub4dos
cp packages/tools/*.7z system/usr/lib/grub4dos
cd system/usr/lib/grub4dos
7z x *.7z
rm *.7z
cd ../../../../

echo "[tools] Setting SUID to udevil"
chown root:root system/usr/bin/udevil
chmod u+s,go-s,ugo+x system/usr/bin/udevil

echo "[tools] Finished!"
