#!/bin/sh

# clean system
#!/bin/sh

echo
echo "Now cleaning system..."
echo

echo "[clean-system] Removing unneeded stuffs..."
rm -rf system/usr/share/man
rm -rf system/usr/share/doc
rm -rf system/usr/share/lintian
rm -rf system/usr/share/menu
rm -rf system/usr/share/initramfs-tools
rm -rf system/usr/share/pkgconfig
rm -rf system/usr/share/mc/examples
rm -rf system/usr/share/mc/help
cp system/usr/share/mc/skins/default.ini system/usr/share/mc
rm -rf system/usr/share/mc/skins
mkdir system/usr/share/mc/skins 
cp system/usr/share/mc/default.ini system/usr/share/mc/skins
rm -rf system/usr/lib/x86_64-linux-gnu/perl/cross-config-5.32.1
rm -rf system/usr/lib/x86_64-linux-gnu/perl/debian-config-data-5.32.1
rm -rf system/usr/lib/mime
rm -rf system/usr/share/aclocal
rm -rf system/usr/share/applications
rm -rf system/usr/share/apport
rm -rf system/usr/share/bug
rm -rf system/usr/share/doc-base
rm -rf system/usr/share/gdb
rm -rf system/usr/share/glvnd
rm -rf system/usr/share/gcc
rm -rf system/usr/share/glib-2.0
rm -rf system/usr/share/info
rm -rf system/usr/share/polkit-1
rm -rf system/usr/share/xsessions
rm -rf system/etc/vulkan
rm -rf system/etc/menu-methods
rm -rf system/etc/init.d/x11-common
rm -rf system/etc/gss
rm -rf system/etc/glvnd
rm -rf system/etc/cron.d
cp -rf system/usr/share/locale/en@boldquot system/usr/share/
cp -rf system/usr/share/locale/en@quot system/usr/share/
rm -rf system/usr/share/locale
mkdir -v system/usr/share/locale
mv -v system/usr/share/en@boldquot system/usr/share/locale
mv -v system/usr/share/en@quot system/usr/share/locale
rm -rf system/usr/share/xfce4
rm -rf system/usr/share/gnome-background-properties
rm -rf system/usr/share/gnome
rm -rf system/usr/share/console-setup
rm -rf system/usr/share/backgrounds
rm -rf system/usr/share/appdata
rm -rf system/usr/share/themes/Greybird-accessibility
rm -rf system/usr/share/themes/Greybird-bright
rm -rf system/usr/share/themes/Greybird-compact
rm -rf system/usr/share/themes/Greybird-dark
rm -rf system/usr/share/themes/Greybird-dark-accessibility
rm -rf system/usr/share/themes/Greybird/gnome-shell
rm -rf system/usr/share/themes/Greybird/gtk-3.0
rm -rf system/usr/share/themes/Greybird/metacity-1
rm -rf system/usr/share/themes/Greybird/plank
rm -rf system/usr/share/themes/Greybird/unity
rm -rf system/usr/share/themes/Greybird/xfce-notify-4.0
rm -rf system/usr/share/themes/Greybird/xfwm4
rm -rf system/usr/share/themes/Greybird/Greybird.emerald

echo "[clean-system] Removing unneeded gconv"
mv -v system/usr/lib/x86_64-linux-gnu/gconv/ANSI_X3.110.so system/usr/lib/x86_64-linux-gnu/gconv/ANSI_X3.110.so.k
mv -v system/usr/lib/x86_64-linux-gnu/gconv/CP1251.so system/usr/lib/x86_64-linux-gnu/gconv/CP1251.so.k
mv -v system/usr/lib/x86_64-linux-gnu/gconv/CP1252.so system/usr/lib/x86_64-linux-gnu/gconv/CP1252.so.k
mv -v system/usr/lib/x86_64-linux-gnu/gconv/IBM437.so system/usr/lib/x86_64-linux-gnu/gconv/IBM437.so.k
mv -v system/usr/lib/x86_64-linux-gnu/gconv/IBM850.so system/usr/lib/x86_64-linux-gnu/gconv/IBM850.so.k
mv -v system/usr/lib/x86_64-linux-gnu/gconv/IBM866.so system/usr/lib/x86_64-linux-gnu/gconv/IBM866.so.k
mv -v system/usr/lib/x86_64-linux-gnu/gconv/ISO8859-15.so system/usr/lib/x86_64-linux-gnu/gconv/ISO8859-15.so.k
mv -v system/usr/lib/x86_64-linux-gnu/gconv/ISO8859-1.so system/usr/lib/x86_64-linux-gnu/gconv/ISO8859-1.so.k
mv -v system/usr/lib/x86_64-linux-gnu/gconv/ISO8859-5.so system/usr/lib/x86_64-linux-gnu/gconv/ISO8859-5.so.k
mv -v system/usr/lib/x86_64-linux-gnu/gconv/KOI8-R.so system/usr/lib/x86_64-linux-gnu/gconv/KOI8-R.so.k
mv -v system/usr/lib/x86_64-linux-gnu/gconv/KOI8-U.so system/usr/lib/x86_64-linux-gnu/gconv/KOI8-U.so.k
mv -v system/usr/lib/x86_64-linux-gnu/gconv/UNICODE.so system/usr/lib/x86_64-linux-gnu/gconv/UNICODE.so.k
mv -v system/usr/lib/x86_64-linux-gnu/gconv/UTF-16.so system/usr/lib/x86_64-linux-gnu/gconv/UTF-16.so.k
rm -v system/usr/lib/x86_64-linux-gnu/gconv/*.so
rm -v system/usr/lib/x86_64-linux-gnu/gconv/*.cache
mv -v system/usr/lib/x86_64-linux-gnu/gconv/ANSI_X3.110.so.k system/usr/lib/x86_64-linux-gnu/gconv/ANSI_X3.110.so
mv -v system/usr/lib/x86_64-linux-gnu/gconv/CP1251.so.k system/usr/lib/x86_64-linux-gnu/gconv/CP1251.so
mv -v system/usr/lib/x86_64-linux-gnu/gconv/CP1252.so.k system/usr/lib/x86_64-linux-gnu/gconv/CP1252.so
mv -v system/usr/lib/x86_64-linux-gnu/gconv/IBM437.so.k system/usr/lib/x86_64-linux-gnu/gconv/IBM437.so
mv -v system/usr/lib/x86_64-linux-gnu/gconv/IBM850.so.k system/usr/lib/x86_64-linux-gnu/gconv/IBM850.so
mv -v system/usr/lib/x86_64-linux-gnu/gconv/IBM866.so.k system/usr/lib/x86_64-linux-gnu/gconv/IBM866.so
mv -v system/usr/lib/x86_64-linux-gnu/gconv/ISO8859-15.so.k system/usr/lib/x86_64-linux-gnu/gconv/ISO8859-15.so
mv -v system/usr/lib/x86_64-linux-gnu/gconv/ISO8859-1.so.k system/usr/lib/x86_64-linux-gnu/gconv/ISO8859-1.so
mv -v system/usr/lib/x86_64-linux-gnu/gconv/ISO8859-5.so.k system/usr/lib/x86_64-linux-gnu/gconv/ISO8859-5.so
mv -v system/usr/lib/x86_64-linux-gnu/gconv/KOI8-R.so.k system/usr/lib/x86_64-linux-gnu/gconv/KOI8-R.so
mv -v system/usr/lib/x86_64-linux-gnu/gconv/KOI8-U.so.k system/usr/lib/x86_64-linux-gnu/gconv/KOI8-U.so
mv -v system/usr/lib/x86_64-linux-gnu/gconv/UNICODE.so.k system/usr/lib/x86_64-linux-gnu/gconv/UNICODE.so
mv -v system/usr/lib/x86_64-linux-gnu/gconv/UTF-16.so.k system/usr/lib/x86_64-linux-gnu/gconv/UTF-16.so

echo "[clean-system] Removing unneeded *.a in /usr/lib"
rm -v system/usr/lib/x86_64-linux-gnu/*.a
rm -v system/usr/lib/*.a

echo "[clean-system] Finished!"

# pack base system into initrd
echo "[pack-rootfs] Packing base system..."
cd system
find . | cpio -o -H newc | xz --format=lzma > ../rootfs.gz
cd ..
chown 1000:1000 rootfs.gz
