#!/bin/sh

. files/etc/os-release

echo
echo "Now making ISO bootable image..."
echo

printf "[iso] Checking if old cdroot directory is available..."
if [ -d ${PWD}/cdroot ]; then
	printf "yes, deleting...\n"
	rm -rf cdroot
else
	printf "no\n"
fi

printf "[iso] Checking if old distrb directory is available..."
if [ -d ${PWD}/distrb ]; then
	printf "yes, deleting...\n"
	rm -rf distrb
else
	printf "no\n"
fi

if [ ! -d "cdroot" ]; then
	echo "[iso] Creating cdroot directory..."
	mkdir -pv cdroot/EFI/boot/
	mkdir -pv cdroot/boot/grub
	mkdir -v cdroot/isolinux
fi

echo "[iso] Copying boot media contents into cdroot directory..."
cp -rv bootloader/BIOS/* cdroot/isolinux
cp -v bootloader/UEFI/grub.cfg cdroot/boot/grub
cp -v bootloader/UEFI/bootx64.efi cdroot/EFI/boot
cp -v rootfs.gz cdroot/boot
cp -v vmlinuz cdroot/boot

if [ ! -d "distrb" ]; then
	echo "[iso] Creating distrb directory..."
	mkdir -v distrb
fi

echo "[iso] Creating EFI image..."
dd if=/dev/zero of=cdroot/boot/grub/efi.img bs=1M count=1
mkfs.vfat cdroot/boot/grub/efi.img
mmd -i cdroot/boot/grub/efi.img efi efi/boot
mcopy -vi cdroot/boot/grub/efi.img bootloader/UEFI/bootx64.efi ::efi/boot/

echo "[iso] Creating ISO9660 bootable image..."
xorriso \
    -as mkisofs \
    -iso-level 3 \
    -o "distrb/Anmincat_$VERSION_ID.iso" \
    -full-iso9660-filenames \
    -volid "ANMINCAT" \
    -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
    -eltorito-boot \
        isolinux/isolinux.bin \
        -no-emul-boot \
        -boot-load-size 4 \
        -boot-info-table \
        --eltorito-catalog isolinux/isolinux.cat \
    -eltorito-alt-boot \
        -e /boot/grub/efi.img \
        -no-emul-boot \
        -isohybrid-gpt-basdat \
    -append_partition 2 0xef cdroot/boot/grub/efi.img \
    "cdroot"

echo "[iso] Calculating md5..."
md5sum distrb/Anmincat_$VERSION_ID.iso > distrb/MD5SUM.txt
cat distrb/MD5SUM.txt

echo "[iso] Calculating sha1sum..."
sha1sum distrb/Anmincat_$VERSION_ID.iso > distrb/SHA1SUM.txt
cat distrb/SHA1SUM.txt

echo "[iso] Calculating sha256..."
sha256sum distrb/Anmincat_$VERSION_ID.iso > distrb/SHA256SUM.txt
cat distrb/SHA256SUM.txt

echo "[iso] Copying files/root/INSTALLED_PACKAGES to PACKAGES.txt..."
cp -rv files/root/PACKAGES distrb/PACKAGES.txt
chown 1000:1000 distrb/PACKAGES.txt
chown 1000:1000 distrb/Anmincat_$VERSION_ID.iso
chown 1000:1000 distrb/MD5SUM.txt
chown 1000:1000 distrb/SHA1SUM.txt
chown 1000:1000 distrb/SHA256SUM.txt

echo "[iso] Finished!"
